BACKOFFICE_ORIGIN = ${BACKOFFICE_ORIGIN}
FRONTOFFICE_ORIGIN = ${FRONTOFFICE_ORIGIN}

FACEBOOK_LOGIN_ORIGIN = ${{ BACKOFFICE_ORIGIN }}
FACEBOOK_REDIRECT_ORIGIN = ${{ BACKOFFICE_ORIGIN }}

GOOGLE_LOGIN_ORIGIN = ${{ BACKOFFICE_ORIGIN }}
GOOGLE_REDIRECT_ORIGIN = ${{ BACKOFFICE_ORIGIN }}

CLOUDINARY_CLOUD_NAME = ${CLOUDINARY_CLOUD_NAME}

BUNNY_STORAGE_ZONE_NAME = ${BUNNY_STORAGE_ZONE_NAME}
BUNNY_PULL_ZONE_NAME = ${BUNNY_PULL_ZONE_NAME}
