BACKOFFICE_ORIGIN = ${BACKOFFICE_ORIGIN}
FRONTOFFICE_ORIGIN = ${FRONTOFFICE_ORIGIN}

FACEBOOK_LOGIN_ORIGIN = ${{ BACKOFFICE_ORIGIN }}
FACEBOOK_REDIRECT_ORIGIN = ${{ BACKOFFICE_ORIGIN }}

GOOGLE_LOGIN_ORIGIN = ${{ BACKOFFICE_ORIGIN }}
GOOGLE_REDIRECT_ORIGIN = ${{ BACKOFFICE_ORIGIN }}