FACEBOOK_CLIENT_ID = ${FACEBOOK_CLIENT_ID}
FACEBOOK_CLIENT_SECRET = ${FACEBOOK_CLIENT_SECRET}

GOOGLE_CLIENT_ID = ${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET = ${GOOGLE_CLIENT_SECRET}

MOJO_AUTH_API_KEY = ${MOJO_AUTH_API_KEY}

CLOUDINARY_CLOUD_NAME = ${CLOUDINARY_CLOUD_NAME}
CLOUDINARY_API_KEY = ${CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET = ${CLOUDINARY_API_SECRET}

DEEPL_API_KEY = ${DEEPL_API_KEY}