FACEBOOK_CLIENT_ID = ${FACEBOOK_CLIENT_ID}
FACEBOOK_CLIENT_SECRET = ${FACEBOOK_CLIENT_SECRET}

GOOGLE_CLIENT_ID = ${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET = ${GOOGLE_CLIENT_SECRET}

MOJO_AUTH_API_KEY = ${MOJO_AUTH_API_KEY}

CLOUDINARY_API_KEY = ${CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET = ${CLOUDINARY_API_SECRET}

BUNNY_STORAGE_ZONE_PASSWORD = ${BUNNY_STORAGE_ZONE_PASSWORD}

DEEPL_API_KEY = ${DEEPL_API_KEY}