# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
#
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Deploy to AWS

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      jdk-version: '19'
      branch: 'staging'

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19
      - name: Checkout ${{ env.branch }} on all submodules
        run: |
            git submodule update --init
            cd kbsx && git checkout ${{ env.branch }} && cd ..
            cd kbs3 && git checkout ${{ env.branch }} && cd ..
            cd modality-fork && git checkout ${{ env.branch }} && cd ..
            cd webfx-extras-fork && git checkout ${{ env.branch }} && cd ..
            cd webfx-fork && git checkout ${{ env.branch }} && cd ..
            cd webfx-platform-fork && git checkout ${{ env.branch }} && cd ..
            cd webfx-stack-fork && git checkout ${{ env.branch }} && cd ..
            cd webfx-parent-fork && git checkout ${{ env.branch }} && cd ..
            cd webfx-stack-parent-fork && git checkout ${{ env.branch }} && cd ..
            cd webfx-lib-javacupruntime-fork && git checkout ${{ env.branch }} && cd ..

      - name: Build with Maven
        run: mvn package -B -P 'vertx-fatjar,gwt-compile'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          FAT_JAR: "kbs3/kbs-server-application-vertx/target/kbs-server-application-vertx-1.0.0-SNAPSHOT-fat.jar"
          BACK_OFFICE_WAR: "kbsx/kbsx-apps/kbsx-backoffice-application-gwt/target/kbsx-backoffice-application-gwt-1.0.0-SNAPSHOT.war"
          FRONT_OFFICE_WAR: "kbsx/kbsx-apps/kbsx-frontoffice-application-gwt/target/kbsx-frontoffice-application-gwt-1.0.0-SNAPSHOT.war"
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.KBS_REPOSITORY }}
          ECR_ACCOUNT_ID: ${{ vars.ECR_ACCOUNT_ID }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}
          ECS_SERVICE: ${{ vars.ECS_SERVICE }}
          KBS_DATABASE_HOST: ${{ secrets.KBS_DATABASE_HOST }}
          KBS_DATABASE_PORT: ${{ secrets.KBS_DATABASE_PORT }}
          KBS_DATABASE_NAME: ${{ secrets.KBS_DATABASE_NAME }}
          KBS_DATABASE_USERNAME: ${{ secrets.KBS_DATABASE_USERNAME }}
          KBS_DATABASE_PASSWORD: ${{ secrets.KBS_DATABASE_PASSWORD }}
          IMAGE_TAG: ${{ github.sha }}
          DOCKER_CONF_DIR: ".github/workflows/docker"
        run: |
          cp $FAT_JAR $DOCKER_CONF_DIR
          cp $BACK_OFFICE_WAR $DOCKER_CONF_DIR
          cp $FRONT_OFFICE_WAR $DOCKER_CONF_DIR
          cd $DOCKER_CONF_DIR
          sed -i "s/__KBS_DATABASE_HOST__/${KBS_DATABASE_HOST}/g" override@modality.base.server.datasource.properties
          sed -i "s/__KBS_DATABASE_PORT__/${KBS_DATABASE_PORT}/g" override@modality.base.server.datasource.properties
          sed -i "s/__KBS_DATABASE_NAME__/${KBS_DATABASE_NAME}/g" override@modality.base.server.datasource.properties
          sed -i "s/__KBS_DATABASE_USERNAME__/${KBS_DATABASE_USERNAME}/g" override@modality.base.server.datasource.properties
          sed -i "s/__KBS_DATABASE_PASSWORD__/${KBS_DATABASE_PASSWORD}/g" override@modality.base.server.datasource.properties
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY
          docker tag  $ECR_REGISTRY/$ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          CLUSTER_STATUS=`aws ecs describe-clusters --clusters ${ECS_CLUSTER} | grep -q ACTIVE`
          if [ "${CLUSTER_STATUS}" == "" ]; then
            echo "The STAGING environment seems not to be running. So not refreshing the application services."
          else
            aws ecs update-service --cluster ${ECS_CLUSTER} --service ${ECS_SERVICE} --force-new-deployment
          fi