name: Prod | Discover Vulnerabilities Using CodeQL

on:
  workflow_dispatch:

jobs:
  CodeQL-Build:
    runs-on: ubuntu-latest

    env:
      jdk-version: '19'
      branch: 'prod'

    permissions:
      security-events: write

    steps:
      # Checkout this repository
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Checkout ${{ env.branch }} on all submodules
        run: |
          git submodule update --init
          cd kbsx && git checkout ${{ env.branch }} && cd ..
          cd kbs3 && git checkout ${{ env.branch }} && cd ..
          cd modality-fork && git checkout ${{ env.branch }} && cd ..
          cd webfx-extras-fork && git checkout ${{ env.branch }} && cd ..
          cd webfx-fork && git checkout ${{ env.branch }} && cd ..
          cd webfx-platform-fork && git checkout ${{ env.branch }} && cd ..
          cd webfx-stack-fork && git checkout ${{ env.branch }} && cd ..
          cd webfx-parent-fork && git checkout ${{ env.branch }} && cd ..
          cd webfx-stack-parent-fork && git checkout ${{ env.branch }} && cd ..
          cd webfx-lib-javacupruntime-fork && git checkout ${{ env.branch }} && cd .. 

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.jdk-version }}

      - name: Build with Maven
        run: mvn package -B

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
